### ISSUE TITLE
Organization Create page

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/invoice#12]
#### Organizatoin qo'shadigan page UI yaratish

- [x] Furqat aka download qilgan template ni downlad qiling. 
- [x] Starter.html ichiga kirib body qismida Organization yaratadigan UI qiling
- [x] QIlib bo'lgach shu issue tagida Screenshot jonating.
- [x] PR qilish shart emas
- [x] Layout pastdagi rasmadagiday bo'lshi kerak

![image](https://user-images.githubusercontent.com/30383473/152356476-91abe9cb-f149-49c8-8966-da4d59eee362.jpeg)

**Comment by KhurshidUmid** [comment]
![image](https://user-images.githubusercontent.com/89694198/152389004-7617253c-1eda-4723-b006-a05d81f9436e.png)

**Comment by wahid-d** [comment]
@KhurshidUmid UI sal eskicharo bo'pqopti. Templateni o'zini ichidagi Forms page ga qarasangiz chyotki formlar bor. O'shalardan olsangiz bo'ladi

**Comment by KhurshidUmid** [comment]
New UI for Create organization view
![image](https://user-images.githubusercontent.com/89694198/152563401-7540bbf0-36c0-437a-966f-449db8321dd2.png)
