### ISSUE TITLE
Contact.cs

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/invoice#14]
### Create Contact entity

Properties:
Guid id
string Name
string Address
string Email
string Phone
Guid OwnerId;
virtual AppUser Owner;

## Add to DbContext

- Add this entity to DbContext

## AppUser ga reference qo'shing

- AppUser ga virtual ICollection<Contact> Contacts qo'shing

## DbContext da OnModelCreating ichida navigation relationship qo'shing

**Comment by Xakimov1610** [comment]
close #14

**Comment by Xakimov1610** [comment]
close https://github.com/ilmhub-uz/invoice/issues/14
