### ISSUE TITLE
Invoice.cs

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/invoice#27]
### Invoice class yarating

Properties:

#### `Invoice.cs`

- [x] Guid Id: Key
- [x] String Number: Required, nvarchar(32)
- [x] string Subject: Required, nvarchar(max)
- [x] string ToEmails: Required, nvarchar(max) (validate comma separated emails) 
- [x] DateTimeOffset CreatedAt: Required
- [x] DateTimeOffset ModifiedAt: Required
- [x] DateTimeOffset PaymentDueAt: Required, Validate that date is in the future
- [x] DateTimeOffset DeliveryDueAt: Required 
- [x] Guid FromId: Required
- [x] virtual Organization From:
- [x]  Guid ToId: Required
- [x] virtual Contact To:
- [x] virtual ICollection<InvoiceItem> Items: 

#### `InvoiceItem.cs`
- [x] Guid Id, Key
- [x] string Name: Required, nvarchar(256)
- [x] int Quantity: Required
- [x] double Rate: Required
- [x] string Currency: Required [USD, UZS, RUB, KRW]
- [x] Guid InvoiceId
- [x] virtual Invoice Invoice

#### Relationships
- Organization entity should have virtual ICollection<Invoice> Invoices
- AppUser should have ICollection<Invoice> Invoices

#### AppDbContext o'zgarishlar
- AppUser, Organization va Invoice; Invoice va InvoiceItem o'rtasida relationshiplar qiling

**Comment by AlisherDe** [comment]
close #27

**Comment by AlisherDe** [comment]
close #31

**Comment by AlisherDe** [comment]
close #31
