### ISSUE TITLE
Complete Register/Login process.

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/invoice#48]
### Register/Login processni yakunlash

Hozir Login/Register view lar va account controller chyotki ishlab turibdi. Endi ularni bir biriga ulab, validationlar va boshqa security check larni o'rnatish kerak.

### Qiladigan ishlar
- [ ] AccountController va Register/Login viewlarni ulash kerak
- [ ] barcha validationlarni ishlaydigan qilish kerak
- [ ] Register va login process larni tugatish kerak
- [ ] Logout ham ishlashi kerak
- [ ] Dashboardga borib chap tarafdagi sidebarni eng tagiga `Logout` qo'yish kerak `<i class="fas fa-sign-out-alt"></i>`
  - [ ]  user login qilmagan bo'lsa hech qachon Dashboardga kela olmaydi. Shuning uchun Login ko'rsatilmaydi.
- [ ] user Register qilgandan keyin database ga qo'shilyotganiga ishonch hosil qiling.

**Comment by wahid-d** [comment]
@muydinjanovv 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/30383473/153397029-26e6fdf4-aa21-4a2d-8024-7e7380d755fa.png">
Mana qarasangiz Layout Options > Fixed Sidebar + custom --- ichida eng tagida bita section bor. O'sha joyga Logout link qo'ysangiz bo'ladi.

**Comment by muydinjanovv** [comment]
#48 issue done! closet
