### ISSUE TITLE
Dashboard Layout yarating

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/invoice#8]
- [x] Dashboard layoutni pastdagi linkda topasiz
- [x] Sidebarda Invoyslar, Korxonalar, Kontaktlar degan linklar bo'lishi kerak

https://github.com/ColorlibHQ/AdminLTE/archive/refs/tags/v3.2.0-rc.zip

**Comment by bekzodkomilov** [comment]
Assalomu alekum 
Mani ohrgi vazifam nma furqat aka qbogandan keyn qlasan didz

**Comment by bekzodkomilov** [comment]
![Screenshot from 2022-02-05 07-54-06](https://user-images.githubusercontent.com/91912882/152626310-ddfaefc7-609c-4dcb-a4ba-35a4e14d92ed.png)


Boladimi @wahid-d
